version: '3.7'

services:
  mongo:    
    image: mongo:4.0
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: akkaTrader

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8031:8081'
    depends_on:
      - "mongo"

  graphite:
    image: graphiteapp/graphite-statsd
    hostname: graphite
    container_name: graphite
    restart: always
    ports:
      - "0:80"

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - '3000:3000'
    links:
        - graphite
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=password

  jaeger:
    image: jaegertracing/all-in-one:1.6
    hostname: jaeger
    restart: always
    ports:
      - '16686:16686'

  lighthouse:
    image: petabridge/lighthouse:latest
    hostname: lighthouse
    ports:
      - '9110:9110'
      - '4053:4053'
    environment:
      ACTORSYSTEM: "AkkaTrader"
      CLUSTER_PORT: 4053
      CLUSTER_IP: "lighthouse"
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      STATSD_PORT: 8125
      STATSD_URL: "graphite"
      JAEGER_AGENT_HOST: "jaeger"

  tradeprocessor:
    image: akka.cqrs.tradeprocessor
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 5110
      MONGO_CONNECTION_STR: "mongodb://mongo:27017/akkaTrader"
      STATSD_PORT: 8125
      STATSD_URL: "graphite"
      JAEGER_AGENT_HOST: "jaeger"
    restart: on-failure
    depends_on:
      - "mongo"
      - "lighthouse"

  traders:
    image: akka.cqrs.traders
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 5110
      STATSD_PORT: 8125
      STATSD_URL: "graphite"
      JAEGER_AGENT_HOST: "jaeger"
    restart: on-failure
    depends_on:
      - "lighthouse"

  pricing-root:
    image: akka.cqrs.pricing
    hostname: pricing-root
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 6055
      CLUSTER_IP: "pricing-root"
      MONGO_CONNECTION_STR: "mongodb://mongo:27017/akkaTrader"
      STATSD_PORT: 8125
      STATSD_URL: "graphite"
      JAEGER_AGENT_HOST: "jaeger"
      ENABLE_PHOBOS: "true"
    restart: on-failure
    depends_on:
      - "mongo"
      - "lighthouse"

  pricing-engine:
    image: akka.cqrs.pricing
    ports:
      - '0:9110'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@lighthouse:4053"
      CLUSTER_PORT: 6055
      MONGO_CONNECTION_STR: "mongodb://mongo:27017/akkaTrader"
      STATSD_PORT: 8125
      STATSD_URL: "graphite"
      JAEGER_AGENT_HOST: "jaeger"
      ENABLE_PHOBOS: "true"
    restart: on-failure
    depends_on:
      - "mongo"
      - "lighthouse"

  pricing-web:
    image: akka.cqrs.pricing.web
    ports:
      - '8999:80'
    environment:
      CLUSTER_SEEDS: "akka.tcp://AkkaTrader@pricing-root:6055"
      CLUSTER_PORT: 16666
      STATSD_PORT: 8125
      STATSD_URL: "graphite"
      JAEGER_AGENT_HOST: "jaeger"
      ENABLE_PHOBOS: "true"
    restart: on-failure
    depends_on:
      - "pricing-engine"