# Pull request validation for Linux against the `dev` and `master` branches
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference
trigger:
  branches:
    include:
      - dev
      - master
      - lesson*
      - start

pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    include: [ dev, master, start, lesson* ] # branch names which will trigger a build

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

jobs:
- template: azure-pipeline.template.yaml
  parameters:
    name: Ubuntu
    vmImage: 'ubuntu-latest'
    scriptFileName: ./build.sh
    scriptArgs: 'all customNuGetSource=$(phobosNuGet)'
