apiVersion: v1
kind: Service
metadata:
  name: pricing
  labels:
    app: pricing
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '80'
spec:
  clusterIP: None
  ports:
  - port: 5110
  selector:
    app: pricing
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pricing
  labels:
    app: pricing
spec:
  serviceName: pricing
  replicas: 2
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      labels:
        app: pricing
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: pricing
        image: akka.cqrs.pricing:0.2.1
        env:
        - name: ACTORSYSTEM
          value: AkkaTrader
        - name: ENABLE_PHOBOS
          value: "true"
        - name: MONGO_CONNECTION_STR
          value: "mongodb://mongodb:27017/akkaTrader"
        - name: STATSD_PORT
          value: "8125"
        - name: STATSD_URL
          value: "statsd-agent"
        - name: JAEGER_AGENT_HOST
          value: "jaeger-agent"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_IP
          value: "$(POD_NAME).pricing"
        - name: CLUSTER_PORT
          value: "5110"
        - name: CLUSTER_SEEDS
          value: akka.tcp://$(ACTORSYSTEM)@lighthouse-0.lighthouse:4053,akka.tcp://$(ACTORSYSTEM)@lighthouse-1.lighthouse:4053,akka.tcp://$(ACTORSYSTEM)@lighthouse-2.lighthouse:4053
        livenessProbe:
          tcpSocket:
            port: 5110
        ports:
        - containerPort: 5110
          protocol: TCP
        - containerPort: 80
          protocol: TCP