apiVersion: v1
kind: Service
metadata:
  namespace: akka-cqrs
  name: traders
  labels:
    app: traders
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '80'
spec:
  clusterIP: None
  ports:
  - port: 5110
  selector:
    app: traders
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: akka-cqrs
  name: traders
  labels:
    app: traders
spec:
  serviceName: traders
  replicas: 2
  selector:
    matchLabels:
      app: traders
  template:
    metadata:
      labels:
        app: traders
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: traders
        image: akka.cqrs.traders:0.2.1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        env:
        - name: ACTORSYSTEM
          value: AkkaTrader
        - name: ENABLE_PHOBOS
          value: "true"
        - name: STATSD_PORT
          value: "8125"
        - name: STATSD_URL
          value: "statsd-agent"
        - name: JAEGER_AGENT_HOST
          value: "jaeger-agent"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_IP
          value: "$(POD_NAME).traders"
        - name: CLUSTER_PORT
          value: "5110"
        - name: CLUSTER_SEEDS
          value: akka.tcp://$(ACTORSYSTEM)@lighthouse-0.lighthouse:4053,akka.tcp://$(ACTORSYSTEM)@lighthouse-1.lighthouse:4053,akka.tcp://$(ACTORSYSTEM)@lighthouse-2.lighthouse:4053
        livenessProbe:
          tcpSocket:
            port: 5110
        ports:
        - containerPort: 5110
          protocol: TCP
        - containerPort: 80
          protocol: TCP